/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.monster.vista;

import ec.edu.monster.controlador.ConvUniController;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ConvUniView extends javax.swing.JFrame {

    /**
     * Creates new form ConvUniView
     */
    public ConvUniView() {
        initComponents();
        this.setLocationRelativeTo(null);
        Limpiar();
    }
     private static final DecimalFormat df = new DecimalFormat("0.######");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCm = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnMm = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnKm = new javax.swing.JButton();
        btnPulgadas = new javax.swing.JButton();
        btnPies = new javax.swing.JButton();
        btnYarda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor Unidades Centímetros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conversor Unidades Centímetros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 350, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Ingrese un valor en centímetros: ");

        txtCm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCm)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 460, 130));

        btnMm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMm.setText("Milímetros");
        btnMm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMmActionPerformed(evt);
            }
        });

        btnM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnM.setText("Metros");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnKm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnKm.setText("Kilómetros");
        btnKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKmActionPerformed(evt);
            }
        });

        btnPulgadas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPulgadas.setText("Pulgadas");
        btnPulgadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulgadasActionPerformed(evt);
            }
        });

        btnPies.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPies.setText("Pies");
        btnPies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiesActionPerformed(evt);
            }
        });

        btnYarda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnYarda.setText("Yardas");
        btnYarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYardaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Seleccione la unidad a convertir");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnPies, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnYarda, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnKm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnMm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPies, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYarda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 460, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file3.jpg"))); // NOI18N
        jLabel2.setText("Conversor Unidades Centímetros");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -140, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMmActionPerformed
        // TODO add your handling code here:
        // Validar entrada
        if (!validarEntrada()) {
            return; 
        }
        //Datos
        double cm = Double.parseDouble(txtCm.getText());        
        //Proceso
        ConvUniController control = new ConvUniController();
        double convMm = control.cmAMm(cm);
        
        //Reporte
        String repo="";
        repo += cm + " cm en Milimetros = "+ df.format(convMm) + " mm"+"\n";
        JOptionPane.showMessageDialog(rootPane, repo);

        
    }//GEN-LAST:event_btnMmActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        // TODO add your handling code here:
        // Validar entrada
        if (!validarEntrada()) {
            return; 
        }
        double cm = Double.parseDouble(txtCm.getText());
        
        //Proceso
        ConvUniController control = new ConvUniController();
        double convM = control.cmAM(cm);
        
        //Reporte
        String repo="";
        repo += cm + " cm en Metros = "+ df.format(convM) + " m"+"\n";
        JOptionPane.showMessageDialog(rootPane, repo);
    }//GEN-LAST:event_btnMActionPerformed

    private void btnKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKmActionPerformed
        // TODO add your handling code here:
        // Validar entrada
        if (!validarEntrada()) {
            return; 
        }
        double cm = Double.parseDouble(txtCm.getText());
        
        //Proceso
        ConvUniController control = new ConvUniController();
        double convKm = control.cmAKm(cm);
        
        //Reporte
        String repo="";
        repo += cm + " cm en Kilometros = "+ df.format(convKm) + " Km"+"\n";
        JOptionPane.showMessageDialog(rootPane, repo);
    }//GEN-LAST:event_btnKmActionPerformed

    private void btnPulgadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulgadasActionPerformed
        // TODO add your handling code here:
        // Validar entrada
        if (!validarEntrada()) {
            return; 
        }
        double cm = Double.parseDouble(txtCm.getText());
        
        //Proceso
        ConvUniController control = new ConvUniController();
        double convPulgadas = control.cmAPulgadas(cm);
        
        //Reporte
        String repo="";
        repo += cm + " cm en Pulgadas = "+ df.format(convPulgadas) + " in"+"\n";
        JOptionPane.showMessageDialog(rootPane, repo);
    }//GEN-LAST:event_btnPulgadasActionPerformed

    private void btnPiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiesActionPerformed
        // TODO add your handling code here:
        // Validar entrada
        if (!validarEntrada()) {
            return; 
        }
        double cm = Double.parseDouble(txtCm.getText());
        
        //Proceso
        ConvUniController control = new ConvUniController();
        double convPies = control.cmAPies(cm);
        
        //Reporte
        String repo="";
        repo += cm + " cm en Pies = "+ df.format(convPies) + " ft"+"\n";
        JOptionPane.showMessageDialog(rootPane, repo);
    }//GEN-LAST:event_btnPiesActionPerformed

    private void btnYardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYardaActionPerformed
        // TODO add your handling code here:
        // Validar entrada
        if (!validarEntrada()) {
            return; 
        }
        double cm = Double.parseDouble(txtCm.getText());
        
        //Proceso
        ConvUniController control = new ConvUniController();
        double convYardas = control.cmAYardas(cm);
        
        //Reporte
        String repo="";
        repo += cm + " cm en Metros = "+  df.format(convYardas) + " yd"+"\n";
        JOptionPane.showMessageDialog(rootPane, repo);
    }//GEN-LAST:event_btnYardaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvUniView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvUniView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvUniView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvUniView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvUniView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKm;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnMm;
    private javax.swing.JButton btnPies;
    private javax.swing.JButton btnPulgadas;
    private javax.swing.JButton btnYarda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCm;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txtCm.setText("");
    }

    private boolean validarEntrada() {
        String inputText = txtCm.getText().replace(",", ".");
        
        if (!inputText.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, ingrese un número válido en centímetros.");
            txtCm.setText("");
            return false;
        }
        
        txtCm.setText(inputText);

        return true;
    }
}
